### ISSUE TITLE
Urgent things TODO before first release

### ISSUE THREAD

**Issue by patrickfuchs** [patrickfuchs/buildH#4]
- [x] Manage options w/wo output traj files.
- [x] Name of output file (containing OP) ;`.out` extension of this file ?
- [x] Change function `quick_dic()`.
- [x] Make dic_lipid.POPC choosable by the user (use builtin function `gettatr()`).
- [x] Use ordered dic for `dic_OP` (so that the OP output is always in the same order).
